### ISSUE TITLE
Church search is broken

### ISSUE THREAD

**Issue by replaid** [ocaorg/chancerydb#14]
When I visit https://chancerydb.int.oca.org/churches and search for `church`

I expect to get an informative response (whether results or no results).

Instead I get a 500 page, with this error behind the scenes:

```
ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 8: ...         MATCH(ch.code, ch.name, ch.city) AGAINST ('OCA-CA-K...
                                                             ^
: 
      SELECT id, church_code `code`, church_name `name`, city, state, country, dioc_name diocese, score FROM ( 
        SELECT *, ch_rank + reg_rank + dioc_rank + juris_rank + state_rank + code_rank + code_start_rank score FROM 
        (
          SELECT 
          ch.id, ch.code church_code, ch.name church_name, ch.city, ch.state, ch.country, 
          inst.institution_name inst_name, reg.name reg_name, dioc.name dioc_name, juris.name juris_name,
          MATCH(ch.code, ch.name, ch.city) AGAINST ('OCA-CA-KAMNCH*' IN BOOLEAN MODE) * 2 ch_rank,
          MATCH(reg.name)   AGAINST('OCA-CA-KAMNCH*' IN BOOLEAN MODE) reg_rank,
          MATCH(dioc.name)  AGAINST('OCA-CA-KAMNCH*' IN BOOLEAN MODE) dioc_rank,
          MATCH(juris.name) AGAINST('OCA-CA-KAMNCH*' IN BOOLEAN MODE) juris_rank,
          (ch.state = 'OCA-CA-KAMNCH')               state_rank,
          (ch.code LIKE '%OCA-CA-KAMNCH%')       * 4 code_rank,
          (ch.code LIKE 'OCA-CA-KAMNCH%') * 7 code_start_rank,
          (juris.id = 777) is_oca
          FROM churches ch
          LEFT JOIN contacts inst  ON inst.id  = ch.contact_id
          LEFT JOIN churches reg   ON reg.id   = ch.region_id
          LEFT JOIN churches dioc  ON dioc.id  = ch.diocese_id
          LEFT JOIN churches juris ON juris.id = ch.jurisdiction_id
        ) search 
      ) totals
      WHERE (score > 0)
      ORDER BY score DESC, is_oca DESC
      LIMIT 20
      ;
    ):
  app/models/suggest_church.rb:46:in `search'
  app/controllers/churches_controller.rb:77:in `suggest'
```

**Comment by replaid** [comment]
Duplicate of #7. Closing.
